spring.datasource.username=arthubdev
spring.datasource.password=arthub
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://postgresql:5432/arthub_devdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.schema=public
server.port=8080
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=LUHOgQspH9ohR9HRp+v0XFA+BJtjK+w3xO2rC2nUezUIRHONd8snGZlyacAopdsMKOmZX6xRMtzysoNd/bA9lg==
security.jwt.expiration-time=3600000
spring.elasticsearch.uris=http://elasticsearch-kindiole-dev.apps.sandbox-m3.1530.p1.openshiftapps.com